spring:
  application:
    name: cityToCity
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 9091
  